### ISSUE TITLE
127.0.0.1和0.0.0.0都无法连接

### ISSUE THREAD

**Issue by zc-nju-med** [geekdada/yasd#1]
![75FF3585-A582-45BD-BECE-D9EDD94CB067](https://user-images.githubusercontent.com/43012058/95041709-0f23bd80-070a-11eb-9612-0365580d705b.png)
![6514CBE2-4A8A-4F9F-A41D-389815D054AF](https://user-images.githubusercontent.com/43012058/95041714-11861780-070a-11eb-96c0-37d9d103cde5.png)

**Comment by lvhe19880210** [comment]
我这是https不行 http可以的

**Comment by geekdada** [comment]
请检查 Safari 的 Adblock 规则，通常安全相关的规则会拦截 YASD 请求本地的 API。
