### ISSUE TITLE
策略组白屏

### ISSUE THREAD

**Issue by 4au** [geekdada/yasd#13]
使用 iOS15 Safari 打开面板策略组会就白屏，然后就无论返回到哪个面板页面都是白屏。用其它浏览器正常。
Surge iOS 部分日志：`2021-11-24 21:34:23.746015 <WARNING> [SGSocket-17732] connectx() return error directly: Error Domain=NSPOSIXErrorDomain Code=49 "Can't assign requested address" UserInfo={NSLocalizedDescription=Can't assign requested address} (Address: 127.0.0.1)
2021-11-24 21:34:23.746633 <WARNING> `

**Comment by geekdada** [comment]
请问有没有尝试过删除这个 Surge 连接点重新连接一次？

**Comment by 4au** [comment]
面板地址默认都是直连的，不管是 Surge 内置的还是用该项目的地址都是一样的情况。而且同时用其它浏览器就没问题，因此应该不是节点问题。主要问题是点其他功能都正常，只要点了策略组就页面空白了，然后点返回也是空白刷新也是空白，只能关闭网页重新从主页打开。端口是 4 位端口。

**Comment by geekdada** [comment]
请问你的 iOS 是 beta 版吗？

**Comment by 4au** [comment]
> 请问你的 iOS 是 beta 版吗？

目前是的，但之前 用iOS 15.1 时也这样。可能是我的浏览器开了哪个不兼容的功能。

**Comment by geekdada** [comment]
如果你在使用 beta 版那你应该也是开发者吧，请问可以帮忙排查一下是哪个选项导致的问题吗？

**Comment by 4au** [comment]
> 

不不，😂我只是个小白，得空我用排除法一个一个试试吧。
