### ISSUE TITLE
请问yasd 能否用url 传递参数

### ISSUE THREAD

**Issue by dante2046** [geekdada/yasd#14]
类似于 aira2 的 http://key@host:port
或是 yacd 的 http://xxx.xxx/?hostname=xxx&port=xxx&secret=xxx这种

经常遇到保存为书签，记住了，还是需要重新敲密码的情况

**Comment by geekdada** [comment]
之前考虑过增加这个支持，但是实际上很少遇到更换浏览器的情况所以觉得优先级很低。
