### ISSUE TITLE
始终无法连接，不知道问题出在哪儿

### ISSUE THREAD

**Issue by Lawrenauh** [geekdada/yasd#15]
设置如下，端口一样，两个密码一样，但无论电脑端还是手机端都死活登录不上……Surge iOS 自带的远程控制器用起来一点问题也没有，即使按照内置的远程控制器配置（相同的主机名、端口号和密码）来填写，yasd也还是一样的错误提示。真不知道问题出现在哪儿了：
<img width="1345" alt="截屏2022-02-06 20 26 05" src="https://user-images.githubusercontent.com/14304354/152680837-cdfe2e93-6baf-47f4-bace-0339589dc369.png">
<img width="587" alt="截屏2022-02-06 20 26 43" src="https://user-images.githubusercontent.com/14304354/152680979-ea1a016f-0e5e-4358-a190-35c0ce3dfa89.png">

**Comment by geekdada** [comment]
远端控制器和 API 要使用不一样的端口号哦

**Comment by Lawrenauh** [comment]
> 远端控制器和 API 要使用不一样的端口号哦

换了不一样的端口号，的确能登陆了！Apple 全家桶（Mac、iPhone、iPad  Safari + Chrome）上一点问题都没有，但 Windows 还是登录不了呀，我主要是为了玩 Oculus quest 在头显浏览器里面切换路线方便，不用摘下来用手机切换，Oculus 里面还是搞不了……

**Comment by Lawrenauh** [comment]
> > 远端控制器和 API 要使用不一样的端口号哦
> 
> 换了不一样的端口号，的确能登陆了！Apple 全家桶（Mac、iPhone、iPad Safari + Chrome）上一点问题都没有，但 Windows 还是登录不了呀，我主要是为了玩 Oculus quest 在头显浏览器里面切换路线方便，不用摘下来用手机切换，Oculus 里面还是搞不了……

补充一下，Win10 和 Oculus 都是连的 Mac mini 上 Surge 配置的 DHCP，iPhone、iPad 也是用的 Surge for Mac 的 DHCP。

**Comment by geekdada** [comment]
Windows 上的哪个浏览器可以重现？

**Comment by Lawrenauh** [comment]
> Windows 上的哪个浏览器可以重现？

**Comment by Lawrenauh** [comment]
> Windows 上的哪个浏览器可以重现？

win10上 chrome 和 edge 都不行（macOS上 chrome可以的），oculus 算是安卓吧，自带浏览器也不行

**Comment by Lawrenauh** [comment]
不好意思，不小心点了 close the issue……

**Comment by geekdada** [comment]
可以在 Chrome 的控制台里看看报错是什么吗

**Comment by linkdesu** [comment]
同样遇到用不了的问题，问题出在用 Surge 做网关 iphone.local 这个局域网域名没有重写为 HTTP API 的地址，并且直接访问局域网地址会遇到 CORS 错误，这个错误应该是 Chrome 的安全策略变化导致的，所以请求根本没有被发送出去。

**Comment by geekdada** [comment]
请问你用的是内置的 YASD 还是公共的版本？CORS 错误的日志是怎样的？

**Comment by linkdesu** [comment]
我用的是的这个版本 http://yasd.nerdynerd.org/ ，这是点击 README.md 里面的 HTTP 链接后打开的页面。

CORS 错误信息如下：

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/858724/155867425-e3e6ab56-9e33-46f8-8155-7778cd47c939.png">

如果按照错误信息将局域网 ip 换成 iphone.local 获得的错误信息如下：

<img width="868" alt="image" src="https://user-images.githubusercontent.com/858724/155867468-01f88e98-4437-4048-8593-7325490bdad0.png">

最后，关于你说的内置的 YASD 是指的 Surge 内置了这个服务吗？我在配置文档里没看到相关文档，不过我确认 HTTP-API 是已经开启了的，可以通过直接访问 192.168.49.3:6171 获得返回。

**Comment by geekdada** [comment]
自 Chrome 94 之后，公网的 HTTP 站点默认将不再被允许访问局域网地址。尽管这一限制可以绕过但我认为不应以牺牲安全的代价换取方便。

最佳的解决方法是开启 Surge 的 HTTPS API，然后使用 https://yasd.royli.dev/ 。

**Comment by linkdesu** [comment]
我看官方文档写的还是 `Only HTTP without TLS is supported currently. Surge only uses GET and POST methods.`， Google 了一下也没发现相关的文章，想请问下具体如何开启 HTTPS API ？有链接可以分享一下吗？

**Comment by geekdada** [comment]
```
http-api-tls = true
```

我回头让老刘更新一下文档。

**Comment by linkdesu** [comment]
我发现如果使用 tls 还要增加一步说明：因为使用的是 Surge 自己创建的证书，所以还是会报 CORS 的错误，这时候**一定要手动打开一次** `https://{{hostname}}:6171/v1/outbound` 页面，然后浏览器会询问是否接受这个有风险的证书，选择接受并继续以后就可以正常使用了

目前已经成功用上了，感谢！顺便再感谢下帮忙推广 [vxtrans](https://www.vx.link/)  😂

**Comment by geekdada** [comment]
之前只有已经使用了 Surge 的 MITM 功能，才会打开这个选项，所以已经信任了这个证书。

不谢哈 😄
