### ISSUE TITLE
Bug: 最近请求详情中的 IP 查询链接错误

### ISSUE THREAD

**Issue by xream** [geekdada/yasd#21]
v2.0.4
macos v5.7.3 (2303)
最近请求详情中的 IP 查询链接为 `https://ip.sb/ip/x.x.x.x%20(Proxy)`
应为 `https://ip.sb/ip/x.x.x.x`
![image](https://github.com/geekdada/yasd/assets/1210282/181d721e-ecd4-45b5-a864-f2463c625e1d)

**Comment by geekdada** [comment]
感谢反馈。

**Comment by geekdada** [comment]
感谢 @PaiJi 这个问题已经修复。我会联系 Surge 更新内置版本。
