### ISSUE TITLE
脚本运行结果超过一屏高度后显示异常

### ISSUE THREAD

**Issue by xream** [geekdada/yasd#23]
建议加个最大高度和可滚动(

**Comment by geekdada** [comment]
请试试 https://github.com/geekdada/yasd/releases/tag/v2.0.7

**Comment by xream** [comment]
> 请试试 https://github.com/geekdada/yasd/releases/tag/v2.0.7

![image](https://github.com/user-attachments/assets/1d7779ff-a61a-45a6-8008-8b55c0dd9496)


好像只加了调试脚本的结果
没有处理这个运行的结果

**Comment by geekdada** [comment]
这次应该是修好了。。
