### ISSUE TITLE
Firefox 89 存在跨域问题

### ISSUE THREAD

**Issue by fgprodigal** [geekdada/yasd#9]
最近才换到Firefox，会报错“已拦截跨源请求：同源策略禁止读取位于 https://xxxx/v1/outbound 的远程资源。（原因：CORS 请求未能成功）。”

Chrome和Edge都是没问题的，希望作者测一下

**Comment by geekdada** [comment]
请问你是否开启了 TLS？

**Comment by fgprodigal** [comment]
> 请问你是否开启了 TLS？

开了

**Comment by geekdada** [comment]
Firefox 的根证书是独立于系统的，你需要在 Firefox 中信任 Surge 的证书。

**Comment by fgprodigal** [comment]
> 
> 
> Firefox 的根证书是独立于系统的，你需要在 Firefox 中信任 Surge 的证书。

解决了
